INSERT INTO wh_questions (wh_type, scenario, question, correct_answer, distractors, hint_1, hint_2, difficulty, grade_min, grade_max) VALUES

-- WHAT (10 questions)
('what', 'Sam put on his raincoat before leaving the house. The rain was coming down hard outside.', 'What did Sam put on?', 'His raincoat', '["His boots", "His backpack"]', 'Look at the first sentence — what clothing item did Sam put on?', 'Sam put on his ___ before leaving.', 1, 3, 5),

('what', 'Maya opened her lunchbox and found a turkey sandwich, an apple, and a small bag of pretzels. She ate the sandwich first.', 'What did Maya find in her lunchbox?', 'A turkey sandwich, an apple, and pretzels', '["A peanut butter sandwich and chips", "A banana and crackers"]', 'Look at the first sentence — it lists everything Maya found.', 'Maya found a turkey sandwich, an ___, and a small bag of ___.', 1, 3, 5),

('what', 'The firefighter climbed the tall ladder to rescue the cat stuck in the oak tree. The cat meowed loudly.', 'What was stuck in the oak tree?', 'A cat', '["A kite", "A squirrel"]', 'Look at what the firefighter was trying to rescue.', 'The firefighter went up to rescue the ___ stuck in the tree.', 1, 3, 4),

('what', 'Carlos forgot his science project on the kitchen table. His mom called the school to let his teacher know.', 'What did Carlos forget?', 'His science project', '["His lunch", "His backpack"]', 'Look at the first sentence — what item is mentioned that Carlos left behind?', 'Carlos forgot his ___ project on the kitchen table.', 1, 3, 5),

('what', 'After the storm, the children found a large branch blocking the sidewalk. They worked together to move it out of the way.', 'What were the children moving?', 'A large branch', '["A pile of leaves", "A broken fence"]', 'Look at what was blocking the sidewalk after the storm.', 'The children moved a large ___ that was blocking the sidewalk.', 2, 3, 6),

('what', 'The librarian held up a thick book with a dragon on the cover and said it was the best adventure story she had ever read. Every student in the class wanted to borrow it.', 'What did the librarian hold up?', 'A thick book with a dragon on the cover', '["A magazine about dragons", "A comic book"]', 'Look at what the librarian was holding during her announcement.', 'The librarian held up a thick ___ with a dragon on the cover.', 2, 4, 7),

('what', 'During the experiment, Priya added vinegar to baking soda in a glass jar. The mixture fizzed and bubbled right away.', 'What did Priya add to the baking soda?', 'Vinegar', '["Water", "Lemon juice"]', 'Look at what Priya poured into the jar with the baking soda.', 'Priya added ___ to the baking soda, which made it fizz.', 2, 4, 7),

('what', 'The museum displayed an ancient bronze helmet that soldiers wore in battle more than two thousand years ago. A guard stood nearby to make sure no one touched it.', 'What was on display at the museum?', 'An ancient bronze helmet', '["A Roman sword", "A clay pottery vase"]', 'Look at the first sentence — what specific object was the museum showing?', 'The museum displayed an ancient bronze ___ from over two thousand years ago.', 3, 5, 8),

('what', 'To build the birdhouse, Marcus needed wooden planks, a hammer, nails, and waterproof paint. He spent the whole afternoon putting it together.', 'What did Marcus need to build the birdhouse?', 'Wooden planks, a hammer, nails, and waterproof paint', '["Glue, scissors, and cardboard", "Bricks, cement, and a trowel"]', 'Look at the list of supplies mentioned in the first sentence.', 'Marcus needed wooden planks, a hammer, ___, and waterproof paint.', 2, 4, 6),

('what', 'The astronaut carried out a spacewalk to replace a broken solar panel on the outside of the space station. The repair took nearly four hours.', 'What was the astronaut replacing?', 'A broken solar panel', '["A cracked window", "A faulty communication antenna"]', 'Look at why the astronaut went outside the space station.', 'The astronaut replaced a broken ___ panel during the spacewalk.', 3, 5, 8),

-- WHERE (10 questions)
('where', 'The dog ran under the porch to get out of the rain. It curled up next to the steps and waited for the storm to pass.', 'Where did the dog go?', 'Under the porch', '["Inside the garage", "Behind the fence"]', 'Look at where the dog went to get out of the rain.', 'The dog ran ___ the porch to stay dry.', 1, 3, 5),

('where', 'Lily left her backpack by the front door so she would not forget it in the morning. She always put it there the night before school.', 'Where did Lily leave her backpack?', 'By the front door', '["On the kitchen counter", "In her bedroom"]', 'Look at where Lily placed her backpack.', 'Lily left her backpack by the front ___.', 1, 3, 5),

('where', 'The treasure map showed that the golden coins were buried beneath the old oak tree at the edge of the forest. The pirates had hidden them there centuries ago.', 'Where were the golden coins buried?', 'Beneath the old oak tree at the edge of the forest', '["Inside a cave by the sea", "Under the floorboards of a ship"]', 'Look at what the treasure map showed about where the coins were hidden.', 'The coins were buried beneath the old ___ tree at the edge of the forest.', 2, 3, 6),

('where', 'During recess, the twins always played on the swings near the big maple tree. Today they had the whole playground to themselves.', 'Where did the twins play during recess?', 'On the swings near the big maple tree', '["On the slide by the fence", "In the sandbox"]', 'Look at the twins'' usual spot during recess.', 'The twins played on the ___ near the big maple tree.', 1, 3, 5),

('where', 'The hikers set up their tent in a clearing beside the river. They could hear the water rushing over the rocks all night long.', 'Where did the hikers set up their tent?', 'In a clearing beside the river', '["At the top of a hill", "Near a waterfall"]', 'Look at where the hikers chose to camp for the night.', 'The hikers set up their tent in a clearing beside the ___.', 2, 4, 7),

('where', 'The new grocery store opened on Main Street, right next to the post office. People from three neighborhoods came to shop there on opening day.', 'Where did the new grocery store open?', 'On Main Street next to the post office', '["On Elm Avenue near the park", "On Oak Road near the library"]', 'Look at the address and landmark mentioned for the store.', 'The grocery store opened on Main Street next to the ___.', 2, 4, 6),

('where', 'Scientists discovered a new species of frog living deep in the rainforest, far from any human settlements. The frogs were bright orange with blue spots.', 'Where was the new frog species discovered?', 'Deep in the rainforest', '["On a remote island in the Pacific", "At the bottom of a freshwater lake"]', 'Look at the habitat where scientists found the new frog.', 'Scientists found the frogs living deep in the ___.', 3, 5, 8),

('where', 'After the game, the team gathered in the locker room to celebrate their championship win. The coach gave a short speech and handed out medals.', 'Where did the team gather after the game?', 'In the locker room', '["On the field near the bleachers", "In the gym lobby"]', 'Look at where the team went after their game to celebrate.', 'The team gathered in the ___ room after the championship game.', 1, 3, 5),

('where', 'The rare painting had been stored in a climate-controlled vault beneath the art museum for over fifty years before it was put on public display.', 'Where was the painting stored?', 'In a climate-controlled vault beneath the art museum', '["In a private collector''s home", "In a warehouse near the harbor"]', 'Look at where the painting was kept before it went on display.', 'The painting was stored in a ___ vault beneath the art museum.', 3, 5, 8),

('where', 'Kevin hid the birthday present inside the hall closet behind the winter coats. He hoped his sister would not find it before her party.', 'Where did Kevin hide the present?', 'Inside the hall closet behind the winter coats', '["Under his bed", "In the garage behind the bikes"]', 'Look at the specific hiding spot Kevin chose in the house.', 'Kevin hid the present inside the hall ___ behind the winter coats.', 2, 3, 6),

-- WHO (10 questions)
('who', 'Ms. Chen handed out the permission slips for the field trip on Friday morning. The students had to return them signed by Monday.', 'Who handed out the permission slips?', 'Ms. Chen', '["The principal", "The school secretary"]', 'Look at the person mentioned at the start of the sentence.', '___ handed out the permission slips on Friday morning.', 1, 3, 5),

('who', 'The school custodian, Mr. Rivera, stayed late every Friday to wax the gym floor. The students loved how shiny it looked on Monday.', 'Who waxed the gym floor?', 'Mr. Rivera, the school custodian', '["The gym teacher", "A hired cleaning crew"]', 'Look at who stayed late on Fridays and what their job was.', 'Mr. Rivera, the school ___, stayed late to wax the gym floor.', 1, 3, 5),

('who', 'When the fire alarm went off, the crossing guard near the front door calmly directed all the students to the safety zone on the soccer field.', 'Who directed the students to the safety zone?', 'The crossing guard', '["The principal", "The head teacher"]', 'Look at who helped move the students during the fire alarm.', 'The ___ guard directed the students to the safety zone.', 2, 3, 6),

('who', 'Rosa Parks refused to give up her seat on the bus in Montgomery, Alabama, in 1955. Her brave act helped spark the Civil Rights Movement.', 'Who refused to give up her seat on the bus?', 'Rosa Parks', '["Harriet Tubman", "Sojourner Truth"]', 'Look at the name of the person at the beginning of the passage.', '___ Parks refused to give up her seat on the bus in 1955.', 2, 4, 7),

('who', 'The youngest player on the team, a ten-year-old named Zoe, scored the winning goal in the final minute of the championship game.', 'Who scored the winning goal?', 'Zoe, the youngest player on the team', '["The team captain", "The coach''s daughter"]', 'Look at the description of the person who scored the goal.', '___, the youngest player, scored the winning goal.', 1, 3, 5),

('who', 'A marine biologist named Dr. Okonkwo spent three years studying the migration patterns of humpback whales in the Pacific Ocean.', 'Who studied the migration patterns of humpback whales?', 'Dr. Okonkwo, a marine biologist', '["A wildlife photographer", "A Navy submarine crew"]', 'Look at the profession and name of the person doing the research.', 'Dr. ___, a marine biologist, studied humpback whale migrations.', 2, 4, 7),

('who', 'At the science fair, three judges carefully reviewed each project before announcing that sixth-grader Amir had won first place for his water filtration model.', 'Who won first place at the science fair?', 'Amir, a sixth-grader', '["A fifth-grader named Elena", "The team from Ms. Park''s class"]', 'Look at who the judges announced as the winner.', 'Sixth-grader ___ won first place for his water filtration model.', 2, 4, 6),

('who', 'The author of the famous novel had lived in a small coastal town all her life, drawing inspiration for her characters from her neighbors.', 'Who wrote the famous novel?', 'The author who lived in a small coastal town', '["A professor at a large university", "A journalist from the city"]', 'Look at who is described at the beginning of the sentence.', 'The ___ of the famous novel lived in a small coastal town.', 3, 5, 8),

('who', 'During the blizzard, a volunteer named James delivered groceries to elderly residents who could not leave their homes. He made twelve trips in one day.', 'Who delivered groceries during the blizzard?', 'James, a volunteer', '["A local firefighter", "A grocery store employee"]', 'Look at the name and role of the person helping during the storm.', 'A volunteer named ___ delivered groceries to elderly residents.', 1, 3, 5),

('who', 'The ancient Egyptian pharaoh Cleopatra VII was known for her intelligence and skill in diplomacy. She could speak nine languages.', 'Who was known for speaking nine languages?', 'Cleopatra VII', '["Queen Nefertiti", "Hatshepsut"]', 'Look at the name of the pharaoh described in the passage.', '___ VII, the Egyptian pharaoh, could speak nine languages.', 3, 5, 8),

-- WHEN (10 questions)
('when', 'After finishing her homework, Mia called her friend to talk about the weekend plans. They chatted for almost an hour.', 'When did Mia call her friend?', 'After finishing her homework', '["Before dinner", "During lunch"]', 'Look for the sequence word that tells you when the phone call happened.', 'Mia called her friend ___ finishing her homework.', 1, 3, 5),

('when', 'First, Leo brushed his teeth. Then he put on his pajamas and climbed into bed. Finally, his dad read him a bedtime story.', 'When did Leo climb into bed?', 'After putting on his pajamas', '["Before brushing his teeth", "After his dad read to him"]', 'Look at the order of events — what happened right before Leo got into bed?', 'Leo put on his pajamas and ___ he climbed into bed.', 1, 3, 5),

('when', 'The school picnic will take place on the last Friday of the school year. Students should bring their own lunch and sunscreen.', 'When will the school picnic take place?', 'On the last Friday of the school year', '["On the first day of summer", "During spring break"]', 'Look for the sentence that tells you the date or time of the picnic.', 'The school picnic will take place on the last ___ of the school year.', 1, 3, 5),

('when', 'During the thunderstorm, all outdoor activities were canceled. Once the storm passed, the coaches called the players back onto the field.', 'When did the coaches call the players back onto the field?', 'Once the storm passed', '["Before the storm arrived", "During halftime"]', 'Look for the phrase that explains when play resumed.', 'Once the storm ___, the coaches called the players back.', 2, 3, 6),

('when', 'Settlers began building the town of Millbrook in the spring of 1842, right after the first group of wagons arrived from the east. By winter, there were already thirty houses.', 'When did settlers begin building Millbrook?', 'In the spring of 1842, after the first wagons arrived', '["In the winter of 1842", "Before they crossed the mountains"]', 'Look for the time words that describe when construction started.', 'Settlers began building in the spring of ___, right after the wagons arrived.', 2, 4, 7),

('when', 'The volcano had been dormant for over two hundred years before it erupted without warning in the early morning hours of April third.', 'When did the volcano erupt?', 'In the early morning hours of April third', '["During a powerful earthquake", "After two hundred days of rumbling"]', 'Look for the specific time the eruption happened.', 'The volcano erupted in the early ___ hours of April third.', 3, 5, 8),

('when', 'Whenever it rained, the stray cat would wait on the porch steps until someone opened the door. It always showed up before the heaviest showers.', 'When would the stray cat wait on the porch?', 'Whenever it rained', '["Only at night", "Every morning at sunrise"]', 'Look for the condition word that explains when the cat appeared.', '___ it rained, the stray cat would wait on the porch.', 2, 3, 6),

('when', 'As soon as the bell rang at three o''clock, students rushed out of the building and onto the waiting buses. The hallways emptied in minutes.', 'When did students rush out of the building?', 'As soon as the bell rang at three o''clock', '["After teachers dismissed each class", "Before the final announcements"]', 'Look for the phrase that says exactly when the students left.', 'As soon as the bell ___ at three o''clock, students rushed out.', 1, 3, 5),

('when', 'The ancient Mayan calendar predicted that a solar eclipse would occur on a specific day, and the astronomers were proven correct to the hour.', 'When did the Mayan astronomers predict the eclipse would happen?', 'On a specific day predicted by their calendar', '["During the summer solstice every year", "At the start of each new century"]', 'Look at what the Mayan calendar was used to predict and when.', 'The Mayan calendar predicted the eclipse would occur on a ___ day.', 3, 5, 8),

('when', 'Before the guests arrived, Julia quickly straightened the cushions, lit a candle, and set out the snacks on the coffee table.', 'When did Julia prepare the living room?', 'Before the guests arrived', '["While the guests were eating", "After everyone went home"]', 'Look for the sequence word at the beginning of the sentence.', '___ the guests arrived, Julia prepared the living room.', 1, 3, 5),

-- WHY (10 questions)
('why', 'Jake put on sunscreen before going to the beach. He did not want to get a painful sunburn from the strong summer sun.', 'Why did Jake put on sunscreen?', 'To protect himself from getting a sunburn', '["Because the water was too cold", "Because his mom made him"]', 'Look at the second sentence — it explains Jake''s reason.', 'Jake put on sunscreen because he did not want to get a ___.', 1, 3, 5),

('why', 'The school closed early because a water pipe in the building had burst and flooded two hallways. Students were sent home at noon.', 'Why did the school close early?', 'Because a water pipe burst and flooded two hallways', '["Because of a snowstorm", "Because the heat was not working"]', 'Look at the reason the school had to send students home.', 'The school closed because a water ___ burst and flooded the hallways.', 1, 3, 5),

('why', 'Emma practiced the piano every day for three months before her recital. She wanted to perform her piece without any mistakes.', 'Why did Emma practice the piano every day?', 'So she could perform without mistakes at her recital', '["Because her parents forced her to", "Because she had a competition at school"]', 'Look at what Emma was working toward with all her practice.', 'Emma practiced every day so she could perform without ___ at her recital.', 2, 3, 6),

('why', 'The construction crew put up orange barriers around the pothole in the road. They needed to warn drivers until the road could be repaired.', 'Why did the crew put up orange barriers?', 'To warn drivers about the pothole until it could be fixed', '["To block off a parade route", "To mark where new sidewalks would go"]', 'Look at the second sentence — it explains the purpose of the barriers.', 'The crew put up barriers to warn ___ about the pothole.', 2, 4, 6),

('why', 'Wolves hunt in packs because working together allows them to bring down prey much larger than any single wolf could catch alone.', 'Why do wolves hunt in packs?', 'Because working together lets them catch larger prey', '["Because wolves are afraid of hunting alone at night", "Because they need to protect their pups"]', 'Look at the reason given for wolves'' group behavior.', 'Wolves hunt in packs because working together lets them catch ___ prey.', 2, 4, 7),

('why', 'The farmer covered the young tomato plants with cloth at night during April. Spring temperatures can still drop below freezing, which would kill the seedlings.', 'Why did the farmer cover the tomato plants?', 'To protect them from freezing temperatures at night', '["To keep bugs from eating the leaves", "To prevent sunburn during hot days"]', 'Look at the reason given in the second sentence for covering the plants.', 'The farmer covered the plants to protect them from ___ temperatures.', 3, 5, 8),

('why', 'Nations signed the international treaty to reduce plastic pollution in the ocean because marine animals were dying after swallowing plastic debris.', 'Why did nations sign the treaty to reduce plastic pollution?', 'Because marine animals were dying from swallowing plastic', '["Because plastic made the ocean water unsafe to swim in", "Because fishing boats were getting tangled in plastic nets"]', 'Look at the reason stated for why the treaty was necessary.', 'Nations signed the treaty because marine animals were dying after swallowing ___.', 3, 5, 8),

('why', 'Amara wore her lucky socks to every soccer game because she had scored three goals the first time she wore them. She believed they brought her good luck.', 'Why did Amara wear her lucky socks to every game?', 'Because she believed they brought her good luck after scoring three goals in them', '["Because they were the team''s official uniform", "Because her coach required special socks"]', 'Look at the reason Amara gave for always wearing the same socks.', 'Amara wore her lucky socks because she believed they brought her ___ luck.', 2, 3, 6),

('why', 'Bees pollinate flowers while searching for nectar to bring back to the hive. Without bees, many plants would not be able to produce seeds or fruit.', 'Why is bee pollination important?', 'Because without bees, many plants cannot produce seeds or fruit', '["Because bees make the flowers bloom faster", "Because bees protect plants from insects"]', 'Look at the second sentence — it explains what would happen without bees.', 'Without bees, many plants cannot produce ___ or fruit.', 3, 5, 8),

('why', 'Theo put a bookmark in his book before turning off the light. He did not want to lose his place and have to search for where he stopped reading.', 'Why did Theo put a bookmark in his book?', 'So he would not lose his place in the story', '["Because he was finished reading for good", "Because his teacher required it"]', 'Look at the second sentence — it explains Theo''s reason for using a bookmark.', 'Theo used a bookmark so he would not ___ his place in the story.', 1, 3, 5),

-- HOW (10 questions)
('how', 'Layla mixed flour, eggs, butter, and sugar in a large bowl, then poured the batter into a pan and baked it in the oven for thirty minutes to make the cake.', 'How did Layla make the cake?', 'By mixing flour, eggs, butter, and sugar, then baking the batter in the oven', '["By buying a premade cake from the store", "By steaming the batter in a pot on the stove"]', 'Look at the steps Layla followed to create the cake.', 'Layla mixed the ingredients, poured the batter into a pan, and ___ it in the oven.', 1, 3, 5),

('how', 'To cross the flooded path, the children carefully stepped on large flat rocks that stuck up above the water. They moved slowly and kept their balance.', 'How did the children cross the flooded path?', 'By stepping carefully on large flat rocks above the water', '["By wading straight through the shallow water", "By building a small bridge from branches"]', 'Look at the method the children used to get across.', 'The children crossed by stepping carefully on large flat ___ above the water.', 2, 3, 6),

('how', 'The beaver builds its dam by cutting down trees with its sharp teeth, then dragging the logs and branches across the stream and packing them in with mud.', 'How does a beaver build its dam?', 'By cutting trees, dragging logs across the stream, and packing them with mud', '["By piling rocks and gravel until the stream is blocked", "By weaving grass and reeds together into a tight mat"]', 'Look at the steps described for how a beaver constructs a dam.', 'The beaver builds its dam by cutting trees, dragging logs, and packing them with ___.', 2, 4, 7),

('how', 'Omar learned to juggle by starting with just one ball, then practicing with two, and finally adding a third only after he could keep the first two in the air consistently.', 'How did Omar learn to juggle?', 'By starting with one ball, then two, then adding a third', '["By watching videos and copying the movements exactly", "By taking a class at the local community center"]', 'Look at the progression Omar used to build his juggling skill.', 'Omar learned by starting with one ball, then two, then ___ a third when ready.', 2, 4, 6),

('how', 'Doctors treat a broken bone by first taking an X-ray to see the fracture, then setting the bone in the correct position, and finally placing a cast around it so it heals properly.', 'How do doctors treat a broken bone?', 'By X-raying it, setting it in position, and putting it in a cast', '["By giving medicine and keeping the patient in bed for weeks", "By using a special machine to fuse the broken pieces back together"]', 'Look at the three steps doctors follow when treating a broken bone.', 'Doctors treat a broken bone by X-raying it, setting it, and placing a ___ around it.', 3, 5, 8),

('how', 'Marisol made her kite by cutting a diamond shape from a sheet of plastic, tying two wooden sticks in a cross to form the frame, attaching the plastic to the frame, and adding a long ribbon tail.', 'How did Marisol make her kite?', 'By cutting plastic, making a wooden frame, attaching the plastic to it, and adding a tail', '["By folding paper into a triangle shape and tying string to the corners", "By stretching fabric over a metal frame she bought at the craft store"]', 'Look at the four steps Marisol followed to build her kite.', 'Marisol cut plastic, made a wooden ___, attached the plastic, and added a ribbon tail.', 2, 4, 6),

('how', 'Ancient Egyptians preserved mummies by first removing the internal organs, then drying the body with a special salt called natron, and finally wrapping it tightly in linen bandages.', 'How did ancient Egyptians preserve mummies?', 'By removing organs, drying the body with natron, and wrapping it in linen', '["By coating the body in beeswax and storing it in a cool cave", "By freezing the body in ice from the mountains"]', 'Look at the three-step process described for creating a mummy.', 'Egyptians removed organs, dried the body with ___, and wrapped it in linen bandages.', 3, 5, 8),

('how', 'The rescue team found the missing hiker by using a search dog to follow his scent trail through the woods and up the mountainside.', 'How did the rescue team find the missing hiker?', 'By using a search dog to follow the hiker''s scent trail', '["By tracking his cell phone signal through the forest", "By following his footprints in the mud"]', 'Look at the specific method the rescue team used to locate the hiker.', 'The rescue team found the hiker by using a search ___ to follow his scent.', 2, 4, 7),

('how', 'Plants make their own food through a process called photosynthesis. They use sunlight, water, and carbon dioxide from the air to produce sugar, which gives them energy to grow.', 'How do plants make their own food?', 'Through photosynthesis, using sunlight, water, and carbon dioxide to make sugar', '["By absorbing nutrients from dead animals in the soil", "By storing energy from moonlight during the night"]', 'Look at the process described and the three ingredients plants use.', 'Plants use sunlight, water, and ___ dioxide to make sugar through photosynthesis.', 3, 5, 8),

('how', 'Nina calmed her nervous dog during the thunderstorm by sitting close to him, speaking softly, and wrapping him in a cozy blanket.', 'How did Nina calm her nervous dog?', 'By sitting close to him, speaking softly, and wrapping him in a blanket', '["By giving him a special treat and sending him to his crate", "By playing loud music to drown out the thunder"]', 'Look at the three things Nina did to help her dog feel better.', 'Nina calmed her dog by sitting close, speaking softly, and wrapping him in a ___.', 1, 3, 5);
